import type { Metadata } from "next";
import { Inter as FontSans, Geist, Geist_Mono, Geostar, Roboto } from "next/font/google";
import "./globals.css";
import StyledJsxRegistry from "./registry";
import { cn } from "@/utils/cn";

const inter = FontSans({
  subsets: ['latin'],
  variable: '--font-sans',
});

const geistSans = Geist({
  variable: "--font-geist-sans",
  subsets: ["latin"],
});

const geistMono = Geist_Mono({
  variable: "--font-geist-mono",
  subsets: ["latin"],
});

const geostar = Geostar({
  weight: "400",
  variable: "--font-Geostar",
  subsets: ["latin"],
});

const roboto = Roboto({
  weight: "400",
  subsets: ["latin"],
});

export const metadata: Metadata = {
  title: "Create Next App test",
  description: "Generated by create next app test",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en" className={cn(inter.variable, 'antialiased')}>
      <body className={`${geistSans.variable} ${geistMono.variable} ${geostar.variable} ${roboto.className}`}>
        <StyledJsxRegistry>{children}</StyledJsxRegistry>
      </body>
    </html>
  );
}
